#configure how much armor does against damage. Valid values are 'armor', 'damage', and 'toughness'. Set to "damage" to not modify damage at this step.
"first damage reduction formula" = "damage"


#configure sudden death protection for armor toughness. Valid values are 'armor', 'damage', and 'toughness'. Set to "damage" to not modify damage at this step.
"second damage reduction formula" = "MAX(MIN(0.25, damage), damage - MAX(0, armor * (1 + toughness * 0.02)))"


#configure the efficiency of protection enchantments. Valid values are 'enchant' and 'damage'. Set to "damage" to not modify damage at this step.
"enchantment damage reduction formula" = "damage * 15 / (15 + (enchant * 1.0))"


#configure how armor degrades. Valid values are 'remaining' and 'max'. Set to 1 to disable.
"armor degradation formula" = "MAX((((remaining / max) - 1) ^ 3) + 1, 0.25)"


#Set to false to only cause the armor value to degrade. This will leave extra attributes such as toughness untouched. If using Project: War Dance, stealth will not degrade regardless of damage.
"universal armor degradation" = false

