#Key bindings listed here will be hidden from the key bindings menu.
#Use this to hide key bindings that are not used by the player.
hide_key_bindings = ["key.l2mods.up", "key.l2mods.down", "key.l2mods.swap", "key.loadToolbarActivator", "key.hotbar.9", "keu.l2mods.alt", "key.hotbar.8", "key.hotbar.7", "key.hotbar.6", "key.hotbar.5", "key.hotbar.4", "key.hotbar.3", "key.hotbar.2", "key.hotbar.1", "key.saveToolbarActivator", "key.l2mods.right", "keu.l2mods.shift", "key.entityculling.toggle", "key.l2mods.left"]

