ServerEvents.recipes(event => {
    event.remove({ id: 'palmon:crafting/shapeless/plank_from_wood' })
    event.remove({ id: 'sophisticatedbackpacks:backpack' })
    event.remove({ id: 'botania:mana_infusion/mana_cookie' })
    event.remove({ id: 'sophisticatedbackpacks:iron_backpack' })
    event.remove({ id: 'sophisticatedbackpacks:iron_backpack_from_copper' })
    event.remove({ id: 'quark:building/crafting/furnaces/deepslate_furnace' })
    event.remove({ id: 'nethersdelight:blackstone_furnace' })
    event.remove({ id: 'quark:building/crafting/furnaces/blackstone_furnace' })
    event.remove({ id: 'palmon:crafting/shapeless/empty_contract' })
    event.remove({ id: 'palmon:crafting/shaped/processing_station' })
    event.remove({ id: 'palmon:crafting/shaped/production_machine' })
    event.remove({ id: 'ad_astra:nasa_workbench' })
    event.remove({ id: 'ad_astra:steel_engine' })
    event.remove({ id: 'ad_astra:steel_tank' })
    event.remove({ id: 'ad_astra:alloying/steel_ingot_from_alloying_iron_ingot_and_coals' })
    event.remove({ id: 'redstone_arsenal:materials/flux_obsidian_rod' })
    event.remove({ id: 'ad_astra:nasa_workbench/tier_2_rocket_from_nasa_workbench' })
    event.remove({ id: 'botania:petal_apothecary/entropinnyum' })
    event.remove({ id: 'computercraft:computer_command' })

    event.remove({ id: 'thermal:machines/press/press_enderium_ingot_to_coin' })
    event.remove({ id: 'thermal:machines/press/press_enderium_nugget_to_coin' })
    event.remove({ id: 'tconstruct:smeltery/casting/metal/enderium/coin_gold_cast' })
    event.remove({ id: 'tconstruct:smeltery/casting/metal/enderium/coin_sand_cast' })
    event.remove({ id: 'thermal:machines/press/press_signalum_ingot_to_coin' })
    event.remove({ id: 'thermal:machines/press/press_signalum_nugget_to_coin' })
    event.remove({ id: 'tconstruct:smeltery/casting/metal/signalum/coin_gold_cast' })
    event.remove({ id: 'tconstruct:smeltery/casting/metal/signalum/coin_sand_cast' })
    event.remove({ id: 'thermal:machines/press/press_lumium_ingot_to_coin' })
    event.remove({ id: 'thermal:machines/press/press_lumium_nugget_to_coin' })
    event.remove({ id: 'tconstruct:smeltery/casting/metal/lumium/coin_gold_cast' })
    event.remove({ id: 'tconstruct:smeltery/casting/metal/lumium/coin_sand_cast' })
    event.remove({ id: 'thermal:machines/press/press_netherite_ingot_to_coin' })
    event.remove({ id: 'tconstruct:smeltery/casting/metal/netherite/coin_gold_cast' })
    event.remove({ id: 'tconstruct:smeltery/casting/metal/netherite/coin_sand_cast' })

    event.remove({ id: 'botania:alfheim_portal' })
    event.remove({ id: 'create:crafting/materials/andesite_alloy' })
    event.remove({ id: 'create:crafting/materials/andesite_alloy_from_zinc' })
    event.remove({ id: 'create:mixing/andesite_alloy' })
    event.remove({ id: 'create:mixing/andesite_alloy_from_zinc' })
    event.remove({ id: 'tconstruct:compat/create/andesite_alloy_iron' })
    event.remove({ id: 'tconstruct:compat/create/andesite_alloy_zinc' })
    event.remove({ id: 'thermal:compat/create/smelter_create_alloy_andesite_alloy' })
    event.remove({ id: 'create:item_application/brass_casing_from_log' })
    event.remove({ id: 'create:item_application/brass_casing_from_wood' })
    event.remove({ id: 'create:item_application/brass_casing_from_log_using_deployer' })
    event.remove({ id: 'create:item_application/brass_casing_from_wood_using_deployer' })

    event.remove({ id: 'tfc_ie_addon:anvil/hammer_head' })

    event.remove({ output: 'minecraft:furnace' })
    event.remove({ output: 'thermal:enderium_coin' })
    event.remove({ output: 'thermal:signalum_coin' })
    event.remove({ output: 'thermal:lumium_coin' })

    event.remove({ input: 'immersiveengineering:hammer', not: {id: 'immersiveengineering:crafting/survey_tools'}})

    event.remove({ output: '#cobblemon:poke_balls' })

    event.remove({type: 'minecraft:crafting_shaped',  output: '#forge:gears'})
    event.remove({type: 'minecraft:crafting_shapeless',  input: 'embers:tinker_hammer'})

})